server {
    listen 80;
    index index.html index.php;
    server_name localhost;
    root /var/www/html/public; # Trỏ thẳng vào thư mục public của Laravel

    location / {
        # Ưu tiên tìm file tĩnh (như index.html), nếu không thấy mới đẩy qua Laravel
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Cấu hình để Nginx gửi các file .php sang container "app" xử lý
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}