<?php

return [
    'brand' => 'SmartLMS.io.vn',
    'name' => 'SmartLMS',
    'developer' => 'NgoTanLoi',
    'pages' => [
        'phan-mem-quan-ly-dao-tao' => [
            'route' => 'marketing.training-management',
            'nav_label' => 'Quản lý đào tạo',
            'title' => 'Phần mềm quản lý đào tạo toàn diện | SmartLMS.io.vn',
            'description' => 'SmartLMS.io.vn quản lý tập trung tài khoản, chương trình, khóa học, lớp, lịch, điểm danh, bài tập, bài kiểm tra, thanh toán và báo cáo đào tạo.',
            'eyebrow' => 'Một dữ liệu xuyên suốt',
            'headline' => 'Phần mềm quản lý đào tạo từ vận hành đến lớp học',
            'lead' => 'SmartLMS.io.vn kết nối các nghiệp vụ vốn thường nằm rời rạc trong nhiều bảng tính: quản trị tài khoản, thiết kế nội dung, tổ chức lớp, lập lịch, đánh giá và theo dõi vận hành.',
            'icon' => 'fa-diagram-project',
            'highlights' => ['3 vai trò phân quyền', 'Quản lý vòng đời đào tạo', 'Báo cáo vận hành tập trung'],
            'features' => [
                ['icon' => 'fa-users-gear', 'title' => 'Quản trị đúng vai trò', 'body' => 'Quản trị viên, giáo viên và học viên nhìn thấy đúng dữ liệu, công cụ và phạm vi được phân công.'],
                ['icon' => 'fa-layer-group', 'title' => 'Nội dung có cấu trúc', 'body' => 'Tổ chức chương trình, khóa học, chương, bài học, học liệu, bài tập và bài kiểm tra trong một luồng rõ ràng.'],
                ['icon' => 'fa-chart-column', 'title' => 'Vận hành có số liệu', 'body' => 'Theo dõi lớp, lịch dạy, điểm danh, kết quả, hợp đồng, thanh toán và báo cáo mà không nhập lại dữ liệu.'],
            ],
            'workflow' => [
                ['title' => 'Thiết kế', 'body' => 'Xây chương trình, khóa học và nội dung chuẩn để tái sử dụng.'],
                ['title' => 'Triển khai', 'body' => 'Gán giáo viên, học viên, khóa học và lịch học cho từng lớp.'],
                ['title' => 'Theo dõi', 'body' => 'Điểm danh, đánh giá, phản hồi và tổng hợp dữ liệu vận hành.'],
            ],
            'faq' => [
                ['question' => 'SmartLMS phù hợp với đơn vị nào?', 'answer' => 'Hệ thống phù hợp với trung tâm đào tạo, trường nghề và đơn vị cần quản lý đồng thời lớp học, lịch, nội dung và đánh giá.'],
                ['question' => 'Dữ liệu có tách riêng theo vai trò không?', 'answer' => 'Có. Quyền truy cập được giới hạn theo vai trò, lớp học, khóa học và quan hệ phân công thực tế.'],
                ['question' => 'Hệ thống có hỗ trợ báo cáo không?', 'answer' => 'Có. SmartLMS tổng hợp dữ liệu giảng dạy, thanh toán và hoạt động đào tạo để xem, xuất Excel hoặc in báo cáo.'],
            ],
        ],
        'quan-ly-lop-hoc' => [
            'route' => 'marketing.class-management',
            'nav_label' => 'Quản lý lớp học',
            'title' => 'Phần mềm quản lý lớp học và học viên | SmartLMS.io.vn',
            'description' => 'Quản lý lớp học, phân công giáo viên, nhập danh sách học viên, gắn khóa học và theo dõi tiến độ lớp trên SmartLMS.io.vn.',
            'eyebrow' => 'Đúng lớp · đúng người · đúng nội dung',
            'headline' => 'Quản lý lớp học tập trung, giảm thao tác thủ công',
            'lead' => 'Từ danh sách học viên đến giáo viên phụ trách và nội dung đang triển khai, SmartLMS giúp mỗi lớp có một không gian quản lý thống nhất và dễ kiểm tra.',
            'icon' => 'fa-school',
            'highlights' => ['Import danh sách học viên', 'Phân công giáo viên', 'Theo dõi tiến độ lớp'],
            'features' => [
                ['icon' => 'fa-user-plus', 'title' => 'Danh sách học viên rõ ràng', 'body' => 'Thêm từng học viên hoặc nhập danh sách, kiểm tra dữ liệu trước khi cập nhật và quản lý trạng thái tài khoản.'],
                ['icon' => 'fa-chalkboard-user', 'title' => 'Phân công có phạm vi', 'body' => 'Gắn giáo viên, khóa học và lịch học vào đúng lớp để tránh lẫn dữ liệu giữa các nhóm học viên.'],
                ['icon' => 'fa-arrow-trend-up', 'title' => 'Theo dõi trong một màn hình', 'body' => 'Xem hoạt động học tập, điểm danh và kết quả liên quan của lớp theo quyền được cấp.'],
            ],
            'workflow' => [
                ['title' => 'Tạo lớp', 'body' => 'Khai báo mã lớp, tên lớp, trạng thái và giáo viên phụ trách.'],
                ['title' => 'Tổ chức', 'body' => 'Nhập học viên, gắn khóa học và chuẩn bị lịch học.'],
                ['title' => 'Vận hành', 'body' => 'Theo dõi danh sách, điểm danh và tiến độ trong suốt khóa học.'],
            ],
            'faq' => [
                ['question' => 'Có thể nhập học viên từ file không?', 'answer' => 'Có. Luồng nhập hỗ trợ xem lại dữ liệu trước khi xác nhận để hạn chế cập nhật nhầm danh sách.'],
                ['question' => 'Một lớp có thể gắn nhiều khóa học không?', 'answer' => 'Có. Lớp có thể được gắn các khóa triển khai phù hợp với kế hoạch đào tạo.'],
                ['question' => 'Giáo viên có thấy lớp không thuộc mình không?', 'answer' => 'Dữ liệu giáo viên được giới hạn theo quan hệ phân công và quyền truy cập của hệ thống.'],
            ],
        ],
        'quan-ly-lich-hoc' => [
            'route' => 'marketing.schedule-management',
            'nav_label' => 'Quản lý lịch học',
            'title' => 'Quản lý lịch học, lịch dạy và xung đột | SmartLMS.io.vn',
            'description' => 'Lập lịch lặp, import Excel, kéo thả, dời lịch hàng loạt và kiểm tra trùng lớp, giáo viên, phòng học trên SmartLMS.io.vn.',
            'eyebrow' => 'Lịch học linh hoạt',
            'headline' => 'Điều chỉnh lịch nhanh mà vẫn kiểm soát xung đột',
            'lead' => 'SmartLMS hỗ trợ lập lịch cho từng lớp và khóa học, tạo chuỗi buổi học, nhập lịch từ Excel và điều chỉnh trực quan khi kế hoạch thay đổi.',
            'icon' => 'fa-calendar-days',
            'highlights' => ['Lịch lặp theo tuần', 'Kéo thả trực quan', 'Kiểm tra trùng lịch'],
            'features' => [
                ['icon' => 'fa-repeat', 'title' => 'Tạo lịch theo chuỗi', 'body' => 'Tạo nhiều buổi theo tuần hoặc cách tuần, xem trước kết quả và lựa chọn phạm vi khi chỉnh sửa.'],
                ['icon' => 'fa-hand-pointer', 'title' => 'Kéo thả như lịch hiện đại', 'body' => 'Dời buổi học trực tiếp trên lịch, xem xung đột và hoàn tác nhanh khi cần.'],
                ['icon' => 'fa-shield-halved', 'title' => 'Chống trùng tài nguyên', 'body' => 'Kiểm tra lớp, giáo viên và phòng học trước khi tạo, sửa, import hoặc dời lịch hàng loạt.'],
            ],
            'workflow' => [
                ['title' => 'Chọn phạm vi', 'body' => 'Lọc lớp, khóa học và khoảng ngày cần lập hoặc điều chỉnh lịch.'],
                ['title' => 'Xem trước', 'body' => 'Kiểm tra các buổi sẽ tạo và những xung đột cần xử lý.'],
                ['title' => 'Áp dụng', 'body' => 'Lưu thay đổi an toàn, ghi nhật ký và hỗ trợ hoàn tác thao tác phù hợp.'],
            ],
            'faq' => [
                ['question' => 'Có thể dời nhiều lịch cùng lúc không?', 'answer' => 'Có. Người quản lý có thể chọn phạm vi và dời đồng loạt theo số ngày hoặc số tuần.'],
                ['question' => 'Import Excel có kiểm tra trùng không?', 'answer' => 'Có. Dữ liệu import được kiểm tra quyền truy cập và xung đột trước khi ghi lịch.'],
                ['question' => 'Học viên xem lịch ở đâu?', 'answer' => 'Học viên có lịch cá nhân được giới hạn theo lớp và khóa học mà mình đang tham gia.'],
            ],
        ],
        'diem-danh-hoc-vien' => [
            'route' => 'marketing.attendance',
            'nav_label' => 'Điểm danh',
            'title' => 'Điểm danh học viên và theo dõi chuyên cần | SmartLMS.io.vn',
            'description' => 'Điểm danh học viên theo lớp, cập nhật trạng thái chuyên cần và theo dõi dữ liệu điểm danh có phân quyền trên SmartLMS.io.vn.',
            'eyebrow' => 'Chuyên cần minh bạch',
            'headline' => 'Điểm danh nhanh, dữ liệu gắn đúng lớp học',
            'lead' => 'SmartLMS đưa thao tác điểm danh vào cùng không gian quản lý lớp, giúp giáo viên cập nhật thuận tiện và học viên chỉ xem dữ liệu của chính mình.',
            'icon' => 'fa-clipboard-check',
            'highlights' => ['Theo danh sách lớp', 'Trạng thái rõ ràng', 'Dữ liệu theo quyền'],
            'features' => [
                ['icon' => 'fa-list-check', 'title' => 'Danh sách sẵn sàng thao tác', 'body' => 'Giáo viên làm việc trực tiếp trên danh sách học viên của lớp với giao diện thích ứng máy tính và thiết bị nhỏ.'],
                ['icon' => 'fa-user-check', 'title' => 'Trạng thái dễ theo dõi', 'body' => 'Ghi nhận tình trạng chuyên cần nhất quán để phục vụ theo dõi lớp và báo cáo liên quan.'],
                ['icon' => 'fa-lock', 'title' => 'Bảo vệ dữ liệu cá nhân', 'body' => 'Học viên chỉ truy cập thông tin điểm danh và kết quả thuộc tài khoản của mình.'],
            ],
            'workflow' => [
                ['title' => 'Mở lớp', 'body' => 'Chọn lớp cần thao tác trong phạm vi giáo viên được phân công.'],
                ['title' => 'Ghi nhận', 'body' => 'Cập nhật trạng thái từng học viên và kiểm tra trước khi lưu.'],
                ['title' => 'Theo dõi', 'body' => 'Sử dụng dữ liệu chuyên cần trong màn hình lớp và báo cáo phù hợp.'],
            ],
            'faq' => [
                ['question' => 'Học viên có thấy điểm danh của bạn cùng lớp không?', 'answer' => 'Không. Màn hình học viên được giới hạn để chỉ hiển thị dữ liệu của chính tài khoản đó.'],
                ['question' => 'Điểm danh có sử dụng trên điện thoại không?', 'answer' => 'Giao diện điểm danh được thiết kế responsive để hỗ trợ thao tác trên nhiều kích thước màn hình.'],
                ['question' => 'Ai được phép cập nhật điểm danh?', 'answer' => 'Quyền cập nhật phụ thuộc vai trò và phạm vi lớp học được hệ thống phân công.'],
            ],
        ],
        'ngan-hang-cau-hoi' => [
            'route' => 'marketing.question-bank',
            'nav_label' => 'Ngân hàng câu hỏi',
            'title' => 'Ngân hàng câu hỏi và tạo bài kiểm tra | SmartLMS.io.vn',
            'description' => 'Tạo, phân loại, import/export Excel, kiểm tra câu trùng và quản lý lịch sử phiên bản câu hỏi trên SmartLMS.io.vn.',
            'eyebrow' => 'Tái sử dụng nội dung đánh giá',
            'headline' => 'Ngân hàng câu hỏi có tổ chức và kiểm soát phiên bản',
            'lead' => 'Giáo viên có thể xây dựng nguồn câu hỏi dùng lại, phân loại theo tag và độ khó, sau đó đưa vào bài kiểm tra theo đúng phạm vi khóa học.',
            'icon' => 'fa-boxes-stacked',
            'highlights' => ['Import và export Excel', 'Phát hiện câu trùng', 'Lịch sử phiên bản'],
            'features' => [
                ['icon' => 'fa-tags', 'title' => 'Phân loại để tìm nhanh', 'body' => 'Lọc câu hỏi theo ngân hàng, loại câu, tag, độ khó và khóa học liên quan.'],
                ['icon' => 'fa-file-excel', 'title' => 'Nhập dữ liệu có xem trước', 'body' => 'Xem trước file Excel, so sánh câu có khả năng trùng và quyết định cách xử lý trước khi lưu.'],
                ['icon' => 'fa-clock-rotate-left', 'title' => 'Theo dõi thay đổi', 'body' => 'Lưu lịch sử phiên bản giúp giáo viên biết nội dung câu hỏi đã thay đổi như thế nào.'],
            ],
            'workflow' => [
                ['title' => 'Tạo nguồn', 'body' => 'Tạo ngân hàng và xác định phạm vi tái sử dụng phù hợp.'],
                ['title' => 'Chuẩn hóa', 'body' => 'Phân loại, xử lý câu trùng và rà soát độ khó của câu hỏi.'],
                ['title' => 'Đánh giá', 'body' => 'Gắn ngân hàng vào khóa học và sử dụng khi tạo bài kiểm tra.'],
            ],
            'faq' => [
                ['question' => 'Có thể nhập câu hỏi hàng loạt không?', 'answer' => 'Có. Hệ thống hỗ trợ luồng import Excel có bước xem trước và kiểm tra dữ liệu trước khi ghi.'],
                ['question' => 'Câu hỏi có dùng lại cho khóa học khác không?', 'answer' => 'Có thể gắn ngân hàng câu hỏi theo phạm vi được giáo viên hoặc quản trị viên cho phép.'],
                ['question' => 'Có xem được nội dung câu hỏi cũ không?', 'answer' => 'Lịch sử phiên bản lưu lại các thay đổi quan trọng để phục vụ rà soát.'],
            ],
        ],
        'chatbot-rag-giao-duc' => [
            'route' => 'marketing.rag-chatbot',
            'nav_label' => 'Chatbot RAG',
            'title' => 'Chatbot RAG giáo dục có trích dẫn nguồn | SmartLMS.io.vn',
            'description' => 'Trợ lý AI SmartLMS tìm kiếm ngữ cảnh từ tài liệu được phép truy cập, trả lời kèm citations, queue và rate limit.',
            'eyebrow' => 'AI có căn cứ',
            'headline' => 'Chatbot RAG trả lời theo tài liệu và quyền truy cập',
            'lead' => 'Thay vì trả lời tách rời dữ liệu giảng dạy, trợ lý SmartLMS truy xuất ngữ cảnh liên quan từ bài học và tài liệu mà người dùng được phép xem.',
            'icon' => 'fa-robot',
            'highlights' => ['Ngữ cảnh theo khóa học', 'Trích dẫn tài liệu', 'Queue và giới hạn yêu cầu'],
            'features' => [
                ['icon' => 'fa-magnifying-glass-chart', 'title' => 'Truy xuất đúng ngữ cảnh', 'body' => 'Tìm kiếm nội dung liên quan trong nguồn kiến thức đang hoạt động và thuộc phạm vi người dùng.'],
                ['icon' => 'fa-quote-left', 'title' => 'Câu trả lời kèm nguồn', 'body' => 'Hiển thị thông tin nguồn tham khảo để người học và giáo viên có thể kiểm tra lại nội dung.'],
                ['icon' => 'fa-gauge-high', 'title' => 'Vận hành có kiểm soát', 'body' => 'Xử lý tác vụ qua hàng đợi, giới hạn tần suất và theo dõi trạng thái để bảo vệ tài nguyên hệ thống.'],
            ],
            'workflow' => [
                ['title' => 'Xác định quyền', 'body' => 'Giới hạn nguồn kiến thức theo người dùng, lớp và khóa học liên quan.'],
                ['title' => 'Truy xuất', 'body' => 'Tìm các đoạn tài liệu phù hợp trước khi xây dựng câu trả lời.'],
                ['title' => 'Phản hồi', 'body' => 'Trả lời bằng tiếng Việt và đính kèm nguồn để người dùng đối chiếu.'],
            ],
            'faq' => [
                ['question' => 'Chatbot có đọc mọi tài liệu trong hệ thống không?', 'answer' => 'Không. Nguồn tìm kiếm được giới hạn theo trạng thái tài liệu và phạm vi truy cập của người dùng.'],
                ['question' => 'Citations dùng để làm gì?', 'answer' => 'Trích dẫn giúp người dùng biết câu trả lời dựa trên tài liệu nào và chủ động kiểm tra lại nội dung gốc.'],
                ['question' => 'Tại sao yêu cầu AI có thể phải chờ?', 'answer' => 'Các tác vụ nặng được đưa vào hàng đợi và giới hạn tần suất để hệ thống ổn định khi nhiều người sử dụng đồng thời.'],
            ],
        ],
        'gioi-thieu-smartlms' => [
            'route' => 'marketing.about',
            'nav_label' => 'Giới thiệu',
            'title' => 'Giới thiệu SmartLMS.io.vn và định hướng phát triển',
            'description' => 'SmartLMS.io.vn là hệ thống quản lý vòng đời đào tạo tích hợp AI, được phát triển tại Việt Nam bởi NgoTanLoi.',
            'eyebrow' => 'SmartLMS.io.vn · Xây dựng tại Việt Nam',
            'headline' => 'SmartLMS cho hoạt động đào tạo thực tế',
            'lead' => 'SmartLMS.io.vn là hệ thống quản lý học tập và vận hành đào tạo do NgoTanLoi phát triển, tập trung vào luồng công việc thực tế của quản trị viên, giáo viên và học viên Việt Nam.',
            'icon' => 'fa-circle-info',
            'highlights' => ['Phát triển tại Việt Nam', 'Tập trung nghiệp vụ thực tế', 'AI hỗ trợ có kiểm soát'],
            'features' => [
                ['icon' => 'fa-route', 'title' => 'Bắt đầu từ quy trình thật', 'body' => 'Các phân hệ được kết nối theo vòng đời từ tài khoản, chương trình, lớp và lịch đến đánh giá và báo cáo.'],
                ['icon' => 'fa-user-shield', 'title' => 'Tôn trọng phạm vi dữ liệu', 'body' => 'Hệ thống ưu tiên phân quyền và cô lập dữ liệu theo vai trò, lớp học và khóa học.'],
                ['icon' => 'fa-brain', 'title' => 'AI là công cụ hỗ trợ', 'body' => 'AI hỗ trợ tìm kiếm, soạn nội dung và phân tích nhưng người dùng vẫn là người kiểm tra và quyết định.'],
            ],
            'workflow' => [
                ['title' => 'Kết nối', 'body' => 'Giảm các điểm đứt gãy giữa quản trị, giảng dạy và học tập.'],
                ['title' => 'Kiểm soát', 'body' => 'Theo dõi quyền, dữ liệu, nhật ký, sao lưu và trạng thái vận hành.'],
                ['title' => 'Cải tiến', 'body' => 'Phát triển theo phản hồi sử dụng và nhu cầu đào tạo thực tế.'],
            ],
            'faq' => [
                ['question' => 'SmartLMS.io.vn có phải hệ thống của Viettel không?', 'answer' => 'Không. SmartLMS.io.vn là sản phẩm độc lập do NgoTanLoi phát triển và không thuộc SmartLMS của Viettel.'],
                ['question' => 'Hệ thống hướng đến đối tượng nào?', 'answer' => 'Sản phẩm hướng đến trung tâm đào tạo, trường nghề, giáo viên và học viên cần một quy trình quản lý thống nhất.'],
                ['question' => 'SmartLMS sử dụng AI như thế nào?', 'answer' => 'AI được dùng cho các tác vụ hỗ trợ như truy xuất tài liệu, gợi ý nội dung và phân tích trong phạm vi quyền cho phép.'],
            ],
        ],
    ],
];
